sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: KgOlmoUYRTK+ez2AdY1jmJYb1pzYWwWpkVku/7qyH6rfnu9ozAH39y0+FOcae4m+fEQ5S/rFR+dFSHiNfoqWWhFvk1T8H/JXmhgP54Q1941So0T+xjKiIZBasGkeJxIrshEBUnqb68zVNsbWQTbmwLEANQgoudWkEpu4D53mcWsJEVt9XU0DIGeQCcEs/yVTYD8p9kjTNOO1KnK/qlN5+S0jamIzbh+0Amre2T0y0hOAMGYsdTRzKQBAdLN0zX+V02DfJcK6W06yM/36+FC3CZiMooLOar33Trhp+JAkBg3gBJT+zCXflEP/mq4pG/QGYkFs3T1neAkuI0SZG507ASX81eRqB2OwZXH7WdV2gBcmSrfViXw2/kBIgNlsWW8k6fzqJ48Oof2k+Kljb/NPmOJbxGejqVyy95rty5R022nJSbyD5M8+tCB7CDZgnnUahYN99tAjujUNgA7Hb4+o4R3XiJh1tdPQLpCGsVNZK+FGe5q9Fmti7tpMXlaPqSq/a3Mc45RY7DuK/5izN4mvMmVII2TAfHpXC5MP5i2MkzkxWiyExx6fXN9UuZrR9sLHnzQFKXzMnA4ajvumbbXGQxXn8ZOTsko/6j+fCl2ZN0bPqjfXSur2qrFWF/tz4jf2SutOCFbCO0+4SjgqR89OhoUnhp2mlb4X5sDCvoudk3g=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Hollow-of-Her-Hand_6045
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy